# Generated by Django 4.2.5 on 2023-11-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("about", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("release_date", models.IntegerField()),
                ("summary", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, related_name="films", to="mod_app.actor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                (
                    "associated_actors",
                    models.ManyToManyField(blank=True, to="mod_app.actor"),
                ),
                (
                    "associated_films",
                    models.ManyToManyField(blank=True, to="mod_app.film"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="genre",
            field=models.ManyToManyField(related_name="genres", to="mod_app.tag"),
        ),
        migrations.AddField(
            model_name="film",
            name="locations",
            field=models.ManyToManyField(blank=True, to="mod_app.location"),
        ),
        migrations.AddField(
            model_name="film",
            name="themes",
            field=models.ManyToManyField(related_name="themes", to="mod_app.tag"),
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="analyses",
                        to="mod_app.film",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actor",
            name="birth_place",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="mod_app.location",
            ),
        ),
        migrations.AddField(
            model_name="actor",
            name="tags",
            field=models.ManyToManyField(related_name="actor_tags", to="mod_app.tag"),
        ),
    ]
