# Generated by Django 4.2.5 on 2023-12-18 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Link"),
        migrations.DeleteModel(name="Drawing"),
        migrations.DeleteModel(name="Postcard"),
        migrations.DeleteModel(name="Poster"),
        migrations.DeleteModel(name="PressBook"),
        migrations.DeleteModel(name="Programme"),
        migrations.DeleteModel(name="Publicity"),
        migrations.DeleteModel(name="Script"),
        migrations.DeleteModel(name="Still"),
        migrations.DeleteModel(name="Source"),
        migrations.DeleteModel(name="FileLink"),
    ]
