# Generated by Django 4.2.5 on 2023-10-30 10:47

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("mod_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="films",
            field=models.ManyToManyField(to="mod_app.film"),
        ),
        migrations.AddField(
            model_name="actor",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("associated_actors", models.ManyToManyField(to="mod_app.actor")),
                ("associated_films", models.ManyToManyField(to="mod_app.film")),
            ],
        ),
        migrations.AddField(
            model_name="actor",
            name="birth_place",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="mod_app.location",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="locations",
            field=models.ManyToManyField(to="mod_app.location"),
        ),
    ]
