# Generated by Django 4.2.5 on 2023-11-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.URLField()),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="short description of what the link is to (optional)",
                        max_length=250,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="analysis",
            options={"verbose_name_plural": "Analyses"},
        ),
        migrations.AddField(
            model_name="film",
            name="alt_titles",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="run_time",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the run time in minutes.",
                null=True,
                verbose_name="Run time in Minutes",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="is_setting",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Copy",
            fields=[
                (
                    "link_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mod_app.link",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="optional name/title for the copy",
                        max_length=100,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("reasonable", "Reasonable"),
                            ("poor", "Poor"),
                            ("fragile", "Fragile"),
                            ("other", "Other"),
                        ],
                        default="reasonable",
                        max_length=10,
                    ),
                ),
                (
                    "condition_comments",
                    models.TextField(
                        help_text="Use this to expand on the condition, particularly if 'Other'"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Copies",
            },
            bases=("mod_app.link",),
        ),
        migrations.AddField(
            model_name="film",
            name="additional_links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to other things",
                null=True,
                related_name="other_links",
                to="mod_app.link",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="source_material",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the source material",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_material_link",
                to="mod_app.link",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="video",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the video file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_link",
                to="mod_app.link",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="copies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to where the copies can be found",
                null=True,
                related_name="copies",
                to="mod_app.copy",
            ),
        ),
    ]
