# Generated by Django 4.2.5 on 2023-11-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_app", "0002_link_alter_analysis_options_film_alt_titles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="additional_links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to other things",
                related_name="other_links",
                to="mod_app.link",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="copies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to where the copies can be found",
                related_name="copies",
                to="mod_app.copy",
            ),
        ),
    ]
