# Generated by Django 4.2.5 on 2023-12-15 13:27

from django.db import migrations, models
import ckeditor.fields
import mod_app.models.teaching_analysis_models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0002_analysis_holdings_analysis_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="films",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_films", to="mod_app.film"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_topics", to="mod_app.tag"
            ),
        ),
        migrations.CreateModel(
            name="TeachingResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "films",
                    models.ManyToManyField(
                        blank=True, related_name="tr_films", to="mod_app.film"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tr_tags", to="mod_app.tag"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="tr_topics", to="mod_app.tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analysis",
            name="teaching_resources",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_tr", to="mod_app.teachingresources"
            ),
        ),
        migrations.AddField(
            model_name="teachingresources",
            name="title",
            field=models.CharField(
                max_length=255,
                default=mod_app.models.teaching_analysis_models.TeachingResources.default_title,
            ),
        ),
        migrations.AlterModelOptions(
            name="teachingresources",
            options={"verbose_name_plural": "Teaching Resources"},
        ),
    ]
