# Generated by Django 4.2.5 on 2023-11-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_app", "0003_alter_film_additional_links_alter_film_copies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "roles",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Director", "Director"),
                            ("Screenplay", "Screenplay"),
                            ("Scenography", "Scenography"),
                            ("Photography", "Photography"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="film",
            old_name="run_time",
            new_name="duration",
        ),
        migrations.RenameField(
            model_name="film",
            old_name="summary",
            new_name="synopsis",
        ),
        migrations.RemoveField(
            model_name="film",
            name="locations",
        ),
        migrations.RemoveField(
            model_name="film",
            name="themes",
        ),
        migrations.AddField(
            model_name="film",
            name="bfi_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="intertitle_photo",
            field=models.ImageField(blank=True, null=True, upload_to="intertitles/"),
        ),
        migrations.AddField(
            model_name="film",
            name="intertitle_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="production_company",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="production_country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="actors",
            field=models.ManyToManyField(
                blank=True,
                related_name="films",
                to="mod_app.actor",
                verbose_name="Cast",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="alt_titles",
            field=models.CharField(
                blank=True,
                help_text="Comma separated values, can be 'Original: Filmname,' or 'Filmname (Original),'",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="films", to="mod_app.crew"
            ),
        ),
    ]
