# Generated by Django 4.2.5 on 2023-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0004_film_format_other_alter_film_format_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="temporary_images",
            field=models.TextField(blank=True),
        ),
    ]
