# Generated by Django 4.2.5 on 2023-10-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mod_app", "0004_alter_actor_tags_alter_film_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="film",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="analyses",
                        to="mod_app.film",
                    ),
                ),
            ],
        ),
    ]
