# Generated by Django 4.2.5 on 2023-12-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0005_alter_crew_options_remove_analysis_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="element",
            field=models.CharField(
                choices=[
                    ("pos", "Scene positive"),
                    ("ctn", "Negative coutertype"),
                    ("intn", "Internegative"),
                    ("lav", "Intermediate positive scene (lavender)"),
                    ("olay", "Titles"),
                ],
                default="pos",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="support",
            field=models.CharField(
                choices=[("S", "Safety"), ("N", "Nitrate")],
                default="S",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="current_length",
            field=models.IntegerField(
                blank=True, help_text="Enter the run time in minutes.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="duration",
            field=models.IntegerField(
                blank=True, help_text="Enter the run time in minutes.", null=True
            ),
        ),
    ]
