# Generated by Django 4.2.5 on 2023-12-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0005_alter_film_temporary_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="films",
            field=models.ManyToManyField(
                blank=True, related_name="analyses", to="mod_app.film"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_tags", to="mod_app.tag"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="teaching_resources",
            field=models.ManyToManyField(
                blank=True, related_name="analyses", to="mod_app.teachingresources"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_topics", to="mod_app.tag"
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.ManyToManyField(
                blank=True, related_name="films", to="mod_app.tag"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="associated_films",
            field=models.ManyToManyField(
                blank=True, related_name="locations", to="mod_app.film"
            ),
        ),
        migrations.AlterField(
            model_name="teachingresources",
            name="films",
            field=models.ManyToManyField(
                blank=True, related_name="trs", to="mod_app.film"
            ),
        ),
    ]
