# Generated by Django 4.2.5 on 2023-12-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0005_alter_film_temporary_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="films",
            field=models.ManyToManyField(
                blank=True, related_name="analyses", to="mod_app.film"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_tags", to="mod_app.tag"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="teaching_resources",
            field=models.ManyToManyField(
                blank=True, related_name="analyses", to="mod_app.teachingresources"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_topics", to="mod_app.tag"
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="additional_links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to other things",
                related_name="other_film_links",
                to="mod_app.link",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="drawings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload drawings",
                related_name="film",
                to="mod_app.drawing",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="format_type",
            field=models.CharField(
                choices=[
                    (35, "35 mm"),
                    (16, "16 mm"),
                    (9.5, "9.5 mm"),
                    (70, "70 mm"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=5,
                verbose_name="format",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.ManyToManyField(
                blank=True, related_name="films", to="mod_app.tag"
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="postcards",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload postcards",
                related_name="film",
                to="mod_app.postcard",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="posters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload posters",
                related_name="film",
                to="mod_app.poster",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="press_books",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload press book file(s)",
                related_name="film",
                to="mod_app.pressbook",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="programmes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload programme file(s)",
                related_name="film",
                to="mod_app.programme",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="pub_mat",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload publicity material file(s)",
                related_name="film",
                to="mod_app.publicity",
                verbose_name="Publicity Materials",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="scripts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload script file(s)",
                related_name="film",
                to="mod_app.script",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="source",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to the source material",
                limit_choices_to={"is_source": True},
                related_name="film_source",
                to="mod_app.source",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="stills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload stills",
                related_name="film",
                to="mod_app.still",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="video",
            field=models.ForeignKey(
                blank=True,
                help_text="Link or upload the video file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="film_video",
                to="mod_app.filelink",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="associated_films",
            field=models.ManyToManyField(
                blank=True, related_name="locations", to="mod_app.film"
            ),
        ),
        migrations.AlterField(
            model_name="teachingresources",
            name="films",
            field=models.ManyToManyField(
                blank=True, related_name="trs", to="mod_app.film"
            ),
        ),
    ]
