# Generated by Django 4.2.5 on 2023-12-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0008_rename_path_link_url_alter_film_is_in_colour_and_more"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="actor",
        #     name="tags",
        #     field=models.ManyToManyField(
        #         blank=True, related_name="actor_tags", to="mod_app.tag"
        #     ),
        # ),
        # migrations.DeleteModel(
        #     name="Actor",
        # ),
        # migrations.DeleteModel(
        #     name="Copy",
        # ),
        # migrations.DeleteModel(
        #     name="Crew",
        # ),
        # migrations.RemoveField(
        #     model_name="copy",
        #     name="link_ptr",
        # ),
        # migrations.RemoveField(
        #     model_name="film",
        #     name="actors",
        # ),
        # migrations.RemoveField(
        #     model_name="film",
        #     name="copies",
        # ),
        # migrations.RemoveField(
        #     model_name="location",
        #     name="associated_actors",
        # ),
    ]
