# Generated by Django 4.2.5 on 2024-01-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0008_use_rich_uploader_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="format_type",
            field=models.CharField(
                choices=[
                    ("16", "16 mm"),
                    ("70", "70 mm"),
                    ("35", "35 mm"),
                    ("9.5", "9.5 mm"),
                    ("other", "Other"),
                ],
                default="35",
                max_length=6,
                verbose_name="format",
            ),
        ),
    ]
