# Generated by Django 4.2.5 on 2023-12-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_app", "0009_alter_actor_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="film",
            name="current_length",
        ),
        migrations.RemoveField(
            model_name="film",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="film",
            name="element",
        ),
        migrations.RemoveField(
            model_name="film",
            name="entry_date",
        ),
        migrations.RemoveField(
            model_name="film",
            name="format_type",
        ),
        migrations.RemoveField(
            model_name="film",
            name="is_in_colour",
        ),
        migrations.RemoveField(
            model_name="film",
            name="rollers",
        ),
        migrations.RemoveField(
            model_name="film",
            name="support",
        ),
        migrations.AddField(
            model_name="copy",
            name="collection",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="copy",
            name="current_length",
            field=models.IntegerField(
                blank=True, help_text="Enter the run time in minutes.", null=True
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="duration",
            field=models.IntegerField(
                blank=True, help_text="Enter the run time in minutes.", null=True
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="element",
            field=models.CharField(
                choices=[
                    ("pos", "Scene positive"),
                    ("ctn", "Negative coutertype"),
                    ("intn", "Internegative"),
                    ("lav", "Intermediate positive scene (lavender)"),
                    ("olay", "Titles"),
                ],
                default="pos",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="entry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="copy",
            name="format_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="format"
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="is_in_colour",
            field=models.BooleanField(
                default=False,
                help_text="Check box in colour and leave blank if black and white (default)",
                verbose_name="in colour?",
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="rollers",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of rollers"
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="support",
            field=models.CharField(
                choices=[("S", "Safety"), ("N", "Nitrate")], default="S", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="copy",
            name="condition_comments",
            field=models.TextField(
                blank=True,
                help_text="Use this to expand on the condition, particularly if 'Other'",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
