# Generated by Django 4.2.5 on 2023-12-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0010a_create_field_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="copies",
        ),
        migrations.RemoveField(
            model_name="location",
            name="associated_actors",
        ),
        migrations.RemoveField(
            model_name="film",
            name="crew",
        ),
        migrations.RemoveField(
            model_name="film",
            name="actors",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="film",
        ),
        migrations.DeleteModel(
            name="Actor",
        ),
        migrations.DeleteModel(
            name="Copy",
        ),
        migrations.DeleteModel(
            name="Crew",
        ),
        migrations.AddField(
            model_name="analysis",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_tags", to="mod_app.tag"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="topics", to="mod_app.tag"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="print_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="print_status_comments",
            field=models.CharField(
                blank=True,
                help_text="Optional comments about the print's status",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="collection",
            field=models.CharField(
                choices=[
                    ("tv", "Television"),
                    ("feat", "Feature Films and Short Fiction"),
                    ("silent", "Silent Film"),
                    ("moving", "Artists' Moving Image"),
                    ("nonfic", "Non-fiction"),
                    ("special", "Special Collections"),
                ],
                default="silent",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="element",
            field=models.CharField(
                choices=[
                    ("pos", "Scene positive"),
                    ("ctn", "Negative coutertype"),
                    ("intn", "Internegative"),
                    ("lav", "Intermediate positive scene (lavender)"),
                    ("olay", "Titles"),
                ],
                default="pos",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.ManyToManyField(
                blank=True, related_name="genres", to="mod_app.tag"
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="support",
            field=models.CharField(
                choices=[("S", "Safety"), ("N", "Nitrate")], default="S", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(
                blank=True, help_text="url to the item you'd like to link"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="film",
            field=models.ManyToManyField(
                blank=True, related_name="films", to="mod_app.film"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="cast",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="crew",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Credits"
            ),
        ),
    ]
