# Generated by Django 4.2.5 on 2023-12-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0010_remove_copy_link_ptr_remove_copies_crew_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filelink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("good", "Good"),
                    ("reasonable", "Reasonable"),
                    ("poor", "Poor"),
                    ("fragile", "Fragile"),
                    ("other", "Other"),
                ],
                default="good",
                max_length=50,
            ),
        ),
    ]
