# Generated by Django 4.2.5 on 2024-01-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0010_bibliography_relations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="otherlink",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pressbook",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publicity",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="still",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.CharField(
                help_text="short description of what the link is to",
                max_length=250,
                null=True,
            ),
        ),
    ]
