# Generated by Django 4.2.5 on 2023-12-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0011_new_models_for_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="additional_links",
        ),
        migrations.AlterField(
            model_name="film",
            name="current_length",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the run time of the BFI copy in minutes.",
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="film",
            name="drawings",
        ),
        migrations.AlterField(
            model_name="film",
            name="duration",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the original run time in minutes.",
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="film",
            name="postcards",
        ),
        migrations.RemoveField(
            model_name="film",
            name="posters",
        ),
        migrations.RemoveField(
            model_name="film",
            name="press_books",
        ),
        migrations.RemoveField(
            model_name="film",
            name="programmes",
        ),
        migrations.RemoveField(
            model_name="film",
            name="pub_mat",
        ),
        migrations.RemoveField(
            model_name="film",
            name="scripts",
        ),
        migrations.RemoveField(
            model_name="film",
            name="source",
        ),
        migrations.RemoveField(
            model_name="film",
            name="stills",
        ),
        migrations.AlterField(
            model_name="film",
            name="video",
            field=models.OneToOneField(
                blank=True,
                help_text="Link or upload the video file",
                limit_choices_to={"video_link__isnull": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_link",
                to="mod_app.filelink",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="additional_links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to other things",
                limit_choices_to={"other_links__isnull": False},
                related_name="other_links",
                to="mod_app.link",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="drawings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload drawings",
                related_name="drawings",
                to="mod_app.drawing",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="postcards",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload postcards",
                related_name="postcards",
                to="mod_app.postcard",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="posters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload posters",
                related_name="posters",
                to="mod_app.poster",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="press_books",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload press book file(s)",
                related_name="press_books",
                to="mod_app.pressbook",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="programmes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload programme file(s)",
                related_name="programmes",
                to="mod_app.programme",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="pub_mat",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload publicity material file(s)",
                related_name="pub_material",
                to="mod_app.publicity",
                verbose_name="Publicity Materials",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="scripts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload script file(s)",
                related_name="scripts",
                to="mod_app.script",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="source",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to the source material",
                limit_choices_to={"source_link__isnull": False},
                related_name="source_link",
                to="mod_app.link",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="stills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload stills",
                related_name="stills",
                to="mod_app.still",
            ),
        ),
    ]
