# Generated by Django 4.2.5 on 2024-01-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0012_teachingresources_clips_alter_film_format_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="format_type",
            field=models.CharField(
                choices=[
                    ("35", "35 mm"),
                    ("70", "70 mm"),
                    ("other", "Other"),
                    ("16", "16 mm"),
                    ("9.5", "9.5 mm"),
                ],
                default="35",
                max_length=5,
                verbose_name="format",
            ),
        ),
        migrations.AlterField(
            model_name="otherlink",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pressbook",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publicity",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="still",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.CharField(
                help_text="short description, required", max_length=250, null=True
            ),
        ),
    ]
