# Generated by Django 4.2.5 on 2023-12-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0012_remove_film_additional_links_remove_film_drawings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filelink",
            name="link_type",
        ),
        migrations.AddField(
            model_name="link",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("scripts", "Scripts"),
                    ("press_books", "Press Books"),
                    ("programmes", "Programmes"),
                    ("pub_mat", "Publicity Materials"),
                    ("stills", "Stills"),
                    ("postcards", "Postcards"),
                    ("posters", "Posters"),
                    ("drawings", "Drawings"),
                    ("video", "Video"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="additional_links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to other things",
                limit_choices_to={"link_type": "other"},
                related_name="other_links",
                to="mod_app.link",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="drawings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload drawings",
                limit_choices_to={"link_type": "drawings"},
                related_name="drawings",
                to="mod_app.filelink",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="postcards",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload postcards",
                limit_choices_to={"link_type": "postcards"},
                related_name="postcards",
                to="mod_app.filelink",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="posters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload posters",
                limit_choices_to={"link_type": "posters"},
                related_name="posters",
                to="mod_app.filelink",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="press_books",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload press book file(s)",
                limit_choices_to={"link_type": "press_books"},
                related_name="press_books",
                to="mod_app.filelink",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="programmes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload programme file(s)",
                limit_choices_to={"link_type": "programmes"},
                related_name="programmes",
                to="mod_app.filelink",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="pub_mat",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload publicity material file(s)",
                limit_choices_to={"link_type": "pub_mat"},
                related_name="pub_material",
                to="mod_app.filelink",
                verbose_name="Publicity Materials",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="scripts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload script file(s)",
                limit_choices_to={"link_type": "scripts"},
                related_name="scripts",
                to="mod_app.filelink",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="stills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to or upload stills",
                limit_choices_to={"link_type": "stills"},
                related_name="stills",
                to="mod_app.filelink",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="video",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the video file",
                limit_choices_to={"link_type": "video"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_link",
                to="mod_app.link",
            ),
        ),
    ]
