# Generated by Django 4.2.5 on 2023-12-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0013_drawing_postcard_poster_pressbook_programme_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="film",
        #     name="additional_links",
        # ),
        migrations.RemoveField(
            model_name="film",
            name="video",
        ),
        migrations.AddField(
            model_name="film",
            name="additional_links",
            field=models.ForeignKey(
                blank=True,
                help_text="Links to other things",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="other_links",
                to="mod_app.link",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="video",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the video",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_link",
                to="mod_app.link",
            ),
        ),
    ]
