# Generated by Django 4.2.5 on 2024-01-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0013_make_link_filelink_description_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="otherlink",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="pressbook",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="publicity",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="still",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="url to the item you'd like to link",
                max_length=500,
            ),
        ),
    ]
