# Generated by Django 4.2.5 on 2023-12-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mod_app",
            "0013_source_alter_film_additional_links_alter_film_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="temporary_images",
            field=models.ImageField(blank=True, upload_to="temp/"),
        ),
    ]
