# Generated by Django 4.2.5 on 2024-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0014_increase_url_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachingresources",
            name="clips",
            field=models.ManyToManyField(
                blank=True, related_name="tr_clips", to="mod_app.video"
            ),
        ),
    ]
