# Generated by Django 4.2.5 on 2023-12-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0014_remove_link_link_type_remove_film_additional_links_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="film",
            name="element",
        ),
        migrations.RemoveField(
            model_name="film",
            name="entry_date",
        ),
        migrations.RemoveField(
            model_name="film",
            name="intertitle_photo",
        ),
        migrations.RemoveField(
            model_name="film",
            name="intertitle_text",
        ),
        migrations.RemoveField(
            model_name="film",
            name="print_status",
        ),
        migrations.RemoveField(
            model_name="film",
            name="print_status_comments",
        ),
        migrations.RemoveField(
            model_name="film",
            name="rollers",
        ),
        migrations.RemoveField(
            model_name="film",
            name="source_material",
        ),
        migrations.AddField(
            model_name="film",
            name="print_comments",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about the print/s",
                max_length=255,
                verbose_name="Notes on Prints",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="source",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the source material",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_link",
                to="mod_app.link",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="support",
            field=models.CharField(
                choices=[("V", "Viewable"), ("M", "Master")], default="V", max_length=1
            ),
        ),
    ]
