# Generated by Django 4.2.5 on 2023-12-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0015_remove_film_collection_remove_film_element_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="additional_links",
            field=models.ForeignKey(
                blank=True,
                help_text="Links to other things",
                limit_choices_to={"other_links__isnull": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="other_links",
                to="mod_app.link",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="source",
            field=models.OneToOneField(
                help_text="Link to the source material",
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                limit_choices_to={"source_link__isnull": False},
                related_name="source_link",
                to="mod_app.link",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="video",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the video file",
                limit_choices_to={"video_link__isnull": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_link",
                to="mod_app.link",
            ),
        ),
    ]
