# Generated by Django 4.2.5 on 2024-01-19 13:06

from django.db import migrations, models
import mod_app.models.support_models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0015_tr_clips_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=mod_app.models.support_models.FileLink.upload_to,
                validators=[mod_app.models.support_models.FileLink.validate_max_size],
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=mod_app.models.support_models.FileLink.upload_to,
                validators=[mod_app.models.support_models.FileLink.validate_max_size],
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=mod_app.models.support_models.FileLink.upload_to,
                validators=[mod_app.models.support_models.FileLink.validate_max_size],
            ),
        ),
        migrations.AlterField(
            model_name="pressbook",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=mod_app.models.support_models.FileLink.upload_to,
                validators=[mod_app.models.support_models.FileLink.validate_max_size],
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=mod_app.models.support_models.FileLink.upload_to,
                validators=[mod_app.models.support_models.FileLink.validate_max_size],
            ),
        ),
        migrations.AlterField(
            model_name="publicity",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=mod_app.models.support_models.FileLink.upload_to,
                validators=[mod_app.models.support_models.FileLink.validate_max_size],
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=mod_app.models.support_models.FileLink.upload_to,
                validators=[mod_app.models.support_models.FileLink.validate_max_size],
            ),
        ),
        migrations.AlterField(
            model_name="still",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=mod_app.models.support_models.FileLink.upload_to,
                validators=[mod_app.models.support_models.FileLink.validate_max_size],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=mod_app.models.support_models.FileLink.upload_to,
                validators=[mod_app.models.support_models.FileLink.validate_max_size],
            ),
        ),
    ]
