# Generated by Django 4.2.5 on 2024-01-29 10:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0015_file_size_validator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="Mentions are available here and will contibute to the bibliography.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="print_comments",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about the print/s. Mentions are available here and will contibute to the bibliography.",
                verbose_name="Notes on Prints",
            ),
        ),
        migrations.AlterField(
            model_name="teachingresources",
            name="material",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="Mentions are available here and will contibute to the bibliography.",
                null=True,
            ),
        ),
    ]
