# Generated by Django 4.2.5 on 2024-01-31 13:23

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0016_alter_help_text_regarding_bib_generation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliographyitem",
            name="full_citation",
            field=ckeditor.fields.RichTextField(
                help_text="Please use Harvard reference list style.  Examples: Author surname, initial. (year). 'Title of article/book/website/photograph'. Available at: URL or DOI where applicable (date accessed).  Please note that the website or photo title should be italicised. For more detailed information and examples visit: https://www5.open.ac.uk/library/referencing-and-plagiarism/quick-guide-to-harvard-referencing-cite-them-right",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bibliographyitem",
            name="short_citation",
            field=models.CharField(
                help_text="Please use Harvard in-text citation style.  Examples: (Author surname, year), or in the case of up to 3 authors: (Author 1 surname, Author 2 surname, Author 3 surname, year), or in the case or more than 3 authors: (Author 1 surname, et al., year) ",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="comments",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, help_text="Internal comments between researchers"
            ),
        ),
    ]
