# Generated by Django 4.2.5 on 2024-03-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0017_alter_help_text_for_citations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="alt_titles",
            field=models.TextField(
                blank=True,
                help_text="Comma separated values, format as 'Filmname (Alternative),'",
                null=True,
            ),
        ),
    ]
