# Generated by Django 4.2.5 on 2024-05-10 13:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0020_temp_images_called_list_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNote",
            options={"verbose_name": "Introduction"},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="Mentions are available here.", null=True
                    ),
                ),
                (
                    "bibliography",
                    models.ManyToManyField(
                        blank=True,
                        help_text="This field updates on save, and some items may not be visible immediately",
                        related_name="project_note",
                        to="mod_app.bibliographyitem",
                    ),
                ),
            ],
        ),
    ]
