# Generated by Django 4.2.5 on 2024-06-05 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0021_add_project_notes_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibliographyitem",
            name="annotation",
            field=ckeditor.fields.RichTextField(
                help_text="Notes on how this item was helpful or relevant, for example.",
                null=True,
            ),
        ),
    ]
