# Generated by Django 4.2.5 on 2024-11-12 09:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0027_film_bfi_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualWrittenInfluences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="Mentions are available here.", null=True
                    ),
                ),
                (
                    "bibliography",
                    models.ManyToManyField(
                        blank=True,
                        help_text="This field updates on save, and some items may not be visible immediately",
                        related_name="vwis",
                        to="mod_app.bibliographyitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visual and Written Influences",
                "verbose_name_plural": "Visual and Written Influences",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name_plural": "Feedback on non-academic Activities",
            },
        ),
    ]
