# Generated by Django 4.2.5 on 2024-12-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0028_visualwritteninfluences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
        migrations.AlterField(
            model_name="otherlink",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
        migrations.AlterField(
            model_name="pressbook",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
        migrations.AlterField(
            model_name="publicity",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
        migrations.AlterField(
            model_name="still",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="mod_app.film",
            ),
        ),
    ]
