# Generated by Django 4.2.5 on 2024-12-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0029_alter_drawing_film_alter_otherlink_film_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualwritteninfluences",
            name="films",
            field=models.ManyToManyField(
                to="mod_app.Film", blank=True, related_name="vwis"
            ),
        ),
    ]
