# Generated by Django 4.2.5 on 2025-01-08 13:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0030_add_films_to_vwi"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualInfluences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="Mentions are available here.", null=True
                    ),
                ),
                (
                    "bibliography",
                    models.ManyToManyField(
                        blank=True,
                        help_text="This field updates on save, and some items may not be visible immediately",
                        related_name="visual_influences",
                        to="mod_app.bibliographyitem",
                    ),
                ),
                (
                    "films",
                    models.ManyToManyField(
                        blank=True, related_name="visual_influences", to="mod_app.film"
                    ),
                ),
            ],
            options={
                "verbose_name": "Visual Influence",
                "verbose_name_plural": "Visual Influences",
            },
        ),
        migrations.CreateModel(
            name="WrittenInfluences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="Mentions are available here.", null=True
                    ),
                ),
                (
                    "bibliography",
                    models.ManyToManyField(
                        blank=True,
                        help_text="This field updates on save, and some items may not be visible immediately",
                        related_name="written_influences",
                        to="mod_app.bibliographyitem",
                    ),
                ),
                (
                    "films",
                    models.ManyToManyField(
                        blank=True, related_name="written_influences", to="mod_app.film"
                    ),
                ),
            ],
            options={
                "verbose_name": "Written Influence",
                "verbose_name_plural": "Written Influences",
            },
        ),
        migrations.DeleteModel(
            name="VisualWrittenInfluences",
        ),
    ]
