# Generated by Django 4.2.5 on 2025-03-03 15:56

from django.db import migrations, models
import django.db.models.deletion
import mod_app.models.support_models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0031_splitting_vwis"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicVisualInfluence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="url to the item you'd like to link",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="short description, required", max_length=250
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mod_app.models.support_models.FileLink.upload_to,
                        validators=[
                            mod_app.models.support_models.FileLink.validate_max_size
                        ],
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="mod_app.film",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Visual Influence",
            },
        ),
        migrations.CreateModel(
            name="CardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="url to the item you'd like to link",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="short description, required", max_length=250
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mod_app.models.support_models.FileLink.upload_to,
                        validators=[
                            mod_app.models.support_models.FileLink.validate_max_size
                        ],
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="mod_app.film",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Image",
            },
        ),
    ]
