# Generated by Django 4.2.5 on 2025-03-25 11:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0033_add_keywords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="tags",
        ),
        migrations.AlterField(
            model_name="bibliographyitem",
            name="annotation",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Notes on how this item was helpful or relevant, for example.",
                null=True,
            ),
        ),
    ]
