# Generated by Django 4.2.5 on 2025-04-11 11:19

from django.db import migrations, models
from django.db.models import Q

import django.db.models.deletion


def transfer_topics(apps, schema_editor):
    topic = apps.get_model("mod_app", "Topic")
    tag = apps.get_model("mod_app", "Tag")
    existing_topics = tag.objects.filter((Q(topic__isnull=False))).distinct()
    print("existing_topics", existing_topics)

    for e_t in existing_topics:
        topic.objects.create(name=e_t.name, is_genre=False)


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0034_remove_analysis_tags_bib_annotation_ blank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "tag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mod_app.tag",
                    ),
                ),
            ],
            bases=("mod_app.tag",),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_topics", to="mod_app.topic"
            ),
        ),
        migrations.AlterField(
            model_name="teachingresources",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="tr_topics", to="mod_app.topic"
            ),
        ),
        migrations.RunPython(transfer_topics, migrations.RunPython.noop),
    ]
