# Generated by Django 4.2.5 on 2025-06-10 14:04

from django.db import migrations, models
from django.db.models import Q


def transfer_topics(apps, schema_editor):
    topic = apps.get_model("mod_app", "Topic")
    tag = apps.get_model("mod_app", "Tag")
    existing_topics = tag.objects.filter((Q(topic__isnull=False))).distinct()
    print("existing_topics", existing_topics)

    for e_t in existing_topics:
        topic.objects.create(name=e_t.name, is_genre=False)


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0035a_add_topic_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="teachingresources",
            name="topics",
        ),
        migrations.AddField(
            model_name="analysis",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_topics", to="mod_app.topic"
            ),
        ),
        migrations.AddField(
            model_name="teachingresources",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="tr_topics", to="mod_app.topic"
            ),
        ),
        migrations.RunPython(transfer_topics, migrations.RunPython.noop),
    ]
