# Generated by Django 4.2.5 on 2025-04-11 11:19

from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0034_remove_analysis_tags_bib_annotation_ blank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "tag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mod_app.tag",
                    ),
                ),
            ],
            bases=("mod_app.tag",),
        ),
    ]
