# Generated by Django 4.2.5 on 2025-04-14 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0035_topic_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bibliographyitem",
            options={"ordering": ["short_citation"]},
        ),
    ]
