# Generated by Django 4.2.5 on 2025-04-14 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "mod_app",
            "0035b_alter_analysis_teaching_resources_topic_field_data_migration",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bibliographyitem",
            options={"ordering": ["short_citation"]},
        ),
    ]
