# Generated by Django 4.2.5 on 2025-04-15 11:47

from django.db import migrations, models
from django.db.models import F

from mod_app.models.support_models import Keyword


def update_keywords_in_films(apps, schema_editor):
    films = apps.get_model("mod_app", "Film")
    for film in films.objects.all():
        if isinstance(film.genre, Keyword):
            film.object.update(keyword=F("genre"))


def reverse_update_keywords_in_films(apps, schema_editor):
    films = apps.get_model("mod_app", "Film")
    for film in films.objects.all():
        if isinstance(film.genre, Keyword):
            film.object.update(keyword=None)


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0036_alter_bibliographyitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="keyword",
            field=models.ManyToManyField(
                blank="True", related_name="films_keyword", to="mod_app.keyword"
            ),
        ),
        migrations.RunPython(
            update_keywords_in_films, reverse_update_keywords_in_films
        ),
    ]
