# Generated by Django 4.2.5 on 2025-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_app", "0036_alter_bibliographyitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="keyword",
            field=models.ManyToManyField(
                related_name="films_keyword", to="mod_app.keyword"
            ),
        ),
    ]
