# Generated by Django 4.2.5 on 2025-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_app", "0036_alter_bibliographyitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardimage",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="drawing",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="postcard",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="poster",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pressbook",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="programme",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="publicity",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="publicvisualinfluence",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="script",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="still",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="video",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="visualinfluences",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="writteninfluences",
            name="archive",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
