# Generated by Django 4.2.5 on 2025-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_app", "0037_add_keyword_field_to_film"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="cardimage",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="postcard",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="poster",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="pressbook",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="publicity",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="publicvisualinfluence",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="still",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_archives", to="mod_app.archive"
            ),
        ),
        migrations.AddField(
            model_name="visualinfluences",
            name="archive",
            field=models.ManyToManyField(
                blank=True,
                related_name="visual_influence_archives",
                to="mod_app.archive",
            ),
        ),
        migrations.AddField(
            model_name="writteninfluences",
            name="archive",
            field=models.ManyToManyField(
                blank=True,
                related_name="written_influence_archives",
                to="mod_app.archive",
            ),
        ),
    ]
