# Generated by Django 4.2.5 on 2025-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_app", "0038_add_archive_model_and_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="topic",
            field=models.ManyToManyField(
                blank=True, related_name="films_topic", to="mod_app.topic"
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="keyword",
            field=models.ManyToManyField(
                blank=True, related_name="films_keyword", to="mod_app.keyword"
            ),
        ),
    ]
