# Generated by Django 4.2.5 on 2025-06-09 12:28

from django.db import migrations


class Migration(migrations.Migration):
    def transfer_keyword_to_topic(apps, schema_editor):
        try:
            Keyword = apps.get_model("mod_app", "Keyword")
            Topic = apps.get_model("mod_app", "Topic")

            for keyword in Keyword.objects.all():
                base_id = keyword.id
                base_name = keyword.name

                keyword.delete()

                Topic.objects.create(id=base_id, name=base_name, is_genre=False)
        except Exception as e:
            print(e)

    dependencies = [
        ("mod_app", "0039_add_topic_field_to_Film"),
    ]

    operations = [
        migrations.RunPython(
            transfer_keyword_to_topic, reverse_code=migrations.RunPython.noop
        )
    ]
