# Generated by Django 4.2.5 on 2025-07-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0040_data_migration_transfer_keyword_to_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="summary",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
