# Generated by Django 4.2.5 on 2025-11-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0041_analysis_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="summary",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
