# Generated by Django 4.2.5 on 2025-10-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_app", "0041_analysis_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Limited to 1,000 characters.",
                max_length=1000,
                null=True,
            ),
        ),
    ]
