# Generated by Django 4.2.5 on 2026-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0042_alter_analysis_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="current_length",
            field=models.CharField(
                blank=True,
                help_text="Enter the length of the print and the units in m or ft, eg. 3000 ft or 500 m",
                max_length=12,
                null=True,
                verbose_name="BFI Print Length",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Enter the original run time in minutes. Please use a period (.) to denote fractions, eg. 10.5 meaning 10 mins 30 seconds",
                max_digits=5,
                null=True,
                verbose_name="Original Runtime",
            ),
        ),
    ]
