# Generated by Django 4.2.5 on 2026-02-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0044_alter_film_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="Enter the original run time in ft or m, eg. 3000 ft or 500 m",
                max_length=12,
                null=True,
                verbose_name="Original Length",
            ),
        ),
    ]
