# Generated by Django 4.2.5 on 2026-04-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0045_alter_film_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="associated_films",
            new_name="films",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="address",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="location",
            name="is_setting",
        ),
        migrations.AddField(
            model_name="film",
            name="date_of_representation",
            field=models.CharField(
                blank=True,
                help_text="The time period the film represents or was set in",
                max_length=255,
                null=True,
            ),
        ),
    ]
