# Generated by Django 4.2.5 on 2026-04-21 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0046_rename_address_location_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Genre", "verbose_name_plural": "Genres"},
        ),
    ]
