# Generated by Django 4.2.5 on 2026-06-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0047_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="support",
            field=models.CharField(
                choices=[("V", "Viewable"), ("M", "Non-Viewable Master")],
                default="V",
                max_length=1,
            ),
        ),
    ]
