# Generated by Django 4.2.5 on 2026-06-05 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0048_alter_film_support"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
    ]
