# Generated by Django 4.2.5 on 2026-08-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mod_app", "0049_alter_tag_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCalendarLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
    ]
