from django.test import Client, TestCase
from django.urls import reverse


class TestViewContextData(TestCase):
    def Setup(self):
        self.client = Client()

    def test_homeview_context(): ...
    def test_film_detailview_context(): ...
    def test_analysis_detailview_context(): ...
    def test_tr_detailview_context(): ...
    def test_tag_listview_context(): ...
    def test_tag_detailview_context(): ...
